const Coarse = () => {
  return (
    <>
      <svg
        version="1.1"
        id="Layer_1"
        xmlns="http://www.w3.org/2000/svg"
        x="0px"
        y="0px"
        viewBox="270.2 -2.1 595.2 595.2"
        enable-background="new 270.2 -2.1 595.2 595.2"
      >
        <ellipse
          id="straight_image"
          class="unselected"
          cx="567.8"
          cy="295.5"
          rx="263.8"
          ry="264"
        ></ellipse>
        <g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="288"
                y1="-1.6"
                x2="288"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="320.6"
                y1="-1.6"
                x2="320.6"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="353.3"
                y1="-1.6"
                x2="353.3"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="386"
                y1="-1.6"
                x2="386"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="418.7"
                y1="-1.6"
                x2="418.7"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="448.4"
                y1="-1.6"
                x2="448.4"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="481"
                y1="-1.6"
                x2="481"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="513.8"
                y1="-1.6"
                x2="513.8"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="546.4"
                y1="-1.6"
                x2="546.4"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="579.1"
                y1="-1.6"
                x2="579.1"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="611.8"
                y1="-1.6"
                x2="611.8"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="644.5"
                y1="-1.6"
                x2="644.5"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="677.2"
                y1="-1.6"
                x2="677.2"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="706.9"
                y1="-1.6"
                x2="706.9"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="739.6"
                y1="-1.6"
                x2="739.6"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="772.2"
                y1="-1.6"
                x2="772.2"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="804.9"
                y1="-1.6"
                x2="804.9"
                y2="592.6"
              ></line>
            </g>
          </g>
          <g>
            <g>
              <line
                fill="none"
                stroke="#FFFFFF"
                stroke-width="4"
                stroke-miterlimit="10"
                x1="837.6"
                y1="-1.6"
                x2="837.6"
                y2="592.6"
              ></line>
            </g>
          </g>
        </g>
      </svg>
    </>
  );
};

export default Coarse;
